[package]
# PPG = Packet PlayGround
name = "ppg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.1.1"
tun-tap = "0.1.3"
etherparse = "0.13.0"
